### ISSUE TITLE
Run order fixing fails

### ISSUE THREAD

**Issue by mangstad** [DCAN-Labs/abcd-dicom2bids#11]
https://github.com/DCAN-Labs/abcd-dicom2bids/blob/46298041abe505c861191b64d64ab488c5b84c48/src/unpack_and_setup.sh#L99

Unless I'm missing something, this seems to fail anytime it has to actually correct the order of runs. This check compares the output of the script to the subject ID, presumably because if there are error messages printed we want to say it failed. However, there are status messages printed here: https://github.com/DCAN-Labs/abcd-dicom2bids/blob/46298041abe505c861191b64d64ab488c5b84c48/src/run_order_fix.py#L217

This happens when the runs are originally misordered, but this script corrects the ordering. But since it printed all the "swapped..." messages, the check in unpack_and_setup.sh fails and exits processing. Am I misunderstanding something about how this should be working?

**Comment by ericearl** [comment]
@perronea or @GregConan , could one of you please elaborate on this point for @mangstad ?

**Comment by GregConan** [comment]
@perronea and @ericearl Do we need that print statement in `run_order_fix.py` for any reason? If not, I can just delete it in a new commit

**Comment by perronea** [comment]
@GregConan in the original code it looped over run_order_fix.py because sometimes it would have to reorder the images twice or even three times in special cases before coming up with the correct order. It would report that the order had been fixed by swapping certain images, but if it was run again it would swap the order further, and finally when run a third time it would simply report the subject ID. Obviously this is not how run_order_fix.py should normally behave. It was an issue in the original repository that never got resolved.

The hotfix would be to have unpack_and_setup.sh loop over the command until it doesn't have to swap the order. The better fix would be to find a subject for which this happens and identify the shortcoming in run_order_fix.py.

**Comment by ericearl** [comment]
@perronea I tasked @GregConan with making a fix sometime in the next couple weeks.  Sorry @mangstad , but I don't think we could turn this around faster than that.

**Comment by mangstad** [comment]
That's not a problem. I was more just worried about it being a bug, or me not understanding what the intended usage was. I can implement looping over it locally.
